MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  LIGHT_HEAD_RCNN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
NUM_GPUS: 4
SOLVER:
  TYPE: 'SGD'
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.005
  GAMMA: 0.1
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 360000
  STEPS: [0, 240000, 320000]
RPN:
  RPN_ON: True
#  CLS_ACTIVATION: softmax
  SIZES: (32, 64, 128, 256, 512)
LIGHT_HEAD_RCNN:
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_METHOD: PSRoIAlignPool
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 1024
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: .